####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

from router import Router
from packet import Packet
import queue
import json


class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.ports = {}
        self.distance_vectors = {self.addr: {self.addr: 0}}
        self.forwarding_table = {}

    def update_and_broadcast(self):
        old_vector = dict(self.distance_vectors[self.addr])
        
        # Khởi tạo lại vector của bản thân với điểm xuất phát là chính nó
        new_vector = {self.addr: 0}
        new_forwarding_table = {}

        # Duyệt qua tất cả các cổng đang kết nối (hàng xóm trực tiếp)
        for port, (neighbor, link_cost) in self.ports.items():
            # Nếu hàng xóm đã chia sẻ distance vector của họ
            if neighbor in self.distance_vectors:
                for dest, dest_cost in self.distance_vectors[neighbor].items():
                    # Công thức Bellman-Ford: D_x(y) = min { c(x,v) + D_v(y) }
                    cost_via_neighbor = link_cost + dest_cost
                    
                    if dest not in new_vector or cost_via_neighbor < new_vector[dest]:
                        new_vector[dest] = cost_via_neighbor
                        new_forwarding_table[dest] = port

        # Cập nhật lại dữ liệu của router
        self.distance_vectors[self.addr] = new_vector
        self.forwarding_table = new_forwarding_table

        # Nếu Vector của bản thân thay đổi HOẶC đây là lần chạy đầu tiên, thực hiện quảng bá
        if old_vector != new_vector:
            self.broadcast_vector()

    def broadcast_vector(self):
        """Gửi Distance Vector của mình tới toàn bộ hàng xóm đang kết nối."""
        # Chuyển đổi vector thành chuỗi JSON để truyền đi bảo an
        packet_content = json.dumps(self.distance_vectors[self.addr])
        
        for port, (neighbor, _) in self.ports.items():
            # Tạo gói tin ROUTING: nguồn là mình, đích là hàng xóm
            routing_packet = Packet(
                kind=Packet.ROUTING,
                src_addr=self.addr,
                dst_addr=neighbor,
                content=packet_content
            )
            self.send(port, routing_packet)

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            if packet.dst_addr in self.forwarding_table:
                next_port = self.forwarding_table[packet.dst_addr]
                self.send(next_port, packet)
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors
            # Gói tin định tuyến từ hàng xóm (Routing Packet)
            neighbor_vector = json.loads(packet.content)
            sender = packet.src_addr
            
            # Lưu lại/Cập nhật vector nhận được từ hàng xóm này
            self.distance_vectors[sender] = neighbor_vector
            
            # Tính toán lại bảng định tuyến
            self.update_and_broadcast()

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        self.ports[port] = (endpoint, cost)
        self.update_and_broadcast()

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        if port in self.ports:
            neighbor, _ = self.ports[port]
            
            # Xóa cổng này khỏi danh sách quản lý
            del self.ports[port]
            
            # Xóa vector khoảng cách cũ của hàng xóm đó vì liên kết đã mất
            if neighbor in self.distance_vectors:
                del self.distance_vectors[neighbor]
                
            # Tính toán lại lộ trình thay thế
            self.update_and_broadcast()

    def handle_time(self, time_ms):
        """Handle current time."""
            # TODO
            #   broadcast the distance vector of this router to neighbors
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # Gửi định kỳ bất kể có thay đổi hay không (chống mất mát gói tin định tuyến)
            self.broadcast_vector()

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"DVrouter({self.addr}) -> FT: {self.forwarding_table}"
